services:
  postgres:
    image: postgres:16-alpine
    container_name: hostal-os-pms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hostal_os_pms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - hostal_os_pms_postgres:/var/lib/postgresql/data

volumes:
  hostal_os_pms_postgres:
